import { buildIndex, indexOptions } from '../src/indexer/build.js';
const { atlas, generation } = await buildIndex(indexOptions(process.argv[2]!));
console.log('root      ', JSON.stringify(atlas.repo.root));
console.log('head      ', JSON.stringify(atlas.repo.head));
console.log('present   ', atlas.history.present);
console.log('walked    ', atlas.history.commitsWalked, 'retained', atlas.history.commitsRetained);
console.log('nodes     ', atlas.nodes.length, 'challenges', atlas.challenges.length);
const byVerb = new Map<string, number>();
for (const c of atlas.challenges) byVerb.set(c.verb, (byVerb.get(c.verb) ?? 0) + 1);
console.log('by verb   ', JSON.stringify([...byVerb].sort()));
console.log('truncations', JSON.stringify(atlas.report.truncations));
console.log('generation null?', generation === null);
